name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt install -y libgl-dev libx11-dev libxi-dev libxrandr-dev libglfw3-dev libfreetype6-dev libopenal-dev libvorbis-dev libogg-dev
    - name: make
      run: make
